{
    "application":      "SCRC",
    "copyright":        "&copy; Vightel, 2013",
    "contact":          "Pat Cappelaere",
    "contact_mail":     "pat@cappelaere.com",
    
    "HOSTBASEURL":      "http://scrc.geobliki.com",
    "PORT":				80
	
}

